/homeを認証ユーザ表示にする
RIFT-tokyo/transcendence-front pull request #20
Opened 2022-02-22 16:48 UTC by nafuka11

## チケットへのリンク

#14

## やったこと

- `/home` で `GET /me` を叩くようにしました。
- `/home` か `/users/:username` かによって、Profileのボタンのテキストを切り替えるようにしました。
  - `/home` ："Edit profile"
  - `/users/:username` ："Follow"

## やらないこと

Follow, Unfollowは区別せずFollowとしています。

## テスト

1. Stoplight Studioを起動し、Security Schemesを削除してMockサーバを立ち上げる
1. `src/api/generated/base.ts` の `BASE_PATH` を `http://localhost:4211` から `http://localhost:3100` に変更する
1. ブラウザのデベロッパーツールを開き、ネットワークタブを選択する
1. `http://localhost:4212/` にアクセス
   - `http://localhost:3100/me` にリクエストが飛んでいることを確認
   - ボタンのテキストが "EDIT PROFILE" であることを確認
1. `http://localhost:4212/users/aa` (aaは任意の文字列)
   - `http://localhost:3100/users/by/aa` にリクエストが飛んでいることを確認
   - ボタンのテキストが "FOLLOW" であることを確認

## その他

以下、より良い書き方があるか気になっている箇所です。

- `UserCard.tsx` の `isOwner` という命名は適切か。
- `UserProfile.tsx` の `!!!username` が理解できるか。

2022-02-22 23:58 UTC, tkomatsu requested changes
今のロジックだと、`/users/:username`に自分の`username`でアクセスした時に他人のページとして表示されません？
`/api/me`は必ず叩き、`/users/:username`だった場合は`/api/users/by/:username`を叩いて、2つのレスポンスからidを確認し、idが一致した場合は自分のページとして表示を、そうでない場合は他人のページとして表示するようにするといいんじゃないかなと思いました。

### 今回のPRに含めなくていいところ
多分、`/api/me`で得た情報はフロントのいろんなところで使うので、Reactのglobalなstateとして保持しておくことに今後変えていく必要があるのかなと思います。
@sasakiyudai 認証が終わった後、ルーティングするところで`GetMe()`して得た情報をglobal stateに格納するようにするといいと思うんだけど、そんな感じでいいかな？

2022-02-23 03:49 UTC, nafuka11 commented
おっしゃる通り、自分の `username` だった時、他人のページとして表示されてしまいますね……。
UserProfile に state `isOwner` を追加して、ご指摘の通り修正したいと思います！

2022-02-23 05:38 UTC, tkomatsu approved these changes
LGTM:+1:

2022-02-23 05:38 UTC, merged

2022-02-23 07:13 UTC, sasakiyudai commented
> ### 今回のPRに含めなくていいところ
> 多分、`/api/me`で得た情報はフロントのいろんなところで使うので、Reactのglobalなstateとして保持しておくことに今後変えていく必要があるのかなと思います。 @sasakiyudai 認証が終わった後、ルーティングするところで`GetMe()`して得た情報をglobal stateに格納するようにするといいと思うんだけど、そんな感じでいいかな？

@tkomatsu 
yes!