フォロワー一覧 & Follow/Unfollowボタン実装
RIFT-tokyo/transcendence-front pull request #24
Opened 2022-03-01 15:13 UTC by nafuka11

## チケットへのリンク

#9

## やったこと

### フォロワー一覧表示

`/home` or `/users/{ログインuserのid}` の時、フォロワー一覧を表示しました。

### Follow/Unfollowボタン

`/home` or `/users/{ログインuserのid}` 以外の時、Follow/Unfollowボタンが表示されます。

- ログインユーザがFollowしているかに応じてFollow/Unfollow表示を切り替えます。
- ボタンをクリックで、
  - apiのリクエストが完了するまで、画面上部にローディングバー表示 & ボタンがdisabled されます。
  - Followボタンなら `PUT /users/following/{userID}` を、Unfollowボタンなら `DELETE /users/following/{userID}` をリクエストします。
  - apiのリクエスト完了により、Follow/Unfollow表示を切り替えます（FollowならUnfollow、UnfollowならFollow）

## やらないこと

- フォロワー一覧Cardのスクロール
- コードのフォーマット

## テスト

1. Stoplight Studioを起動し、Security Schemesを削除してMockサーバを立ち上げる
1. `src/api/generated/base.ts` の `BASE_PATH` を `http://localhost:3100` に変更する
1. ブラウザのデベロッパーツールを開き、ネットワークタブを選択する
1. `http://localhost:4212/home` にアクセス
   - アバター画像下のボタン："EDIT PROFILE" であることを確認
   - Followings欄：複数ユーザが表示されていることを確認
1. `http://localhost:4212/users/john` にアクセス
   - アバター画像下のボタン："FOLLOW" であることを確認
   - Followings欄が表示されないことを確認
   - "FOLLOW" ボタンをクリックし、
     - 画面
       - 画面上部にローディングバーが表示されることを確認
       - ボタンのテキストが "UNFOLLOW" に切り替わることを確認
     - ネットワークタブ
       - `PUT /users/following/{userID}` にリクエストが飛ぶことを確認
   - "UNFOLLOW" ボタンをクリックし、
     - 画面
       - 画面上部にローディングバーが表示されることを確認
       - ボタンのテキストが "FOLLOW" に切り替わることを確認
     - ネットワークタブ
       - `DELETE /users/following/{userID}` にリクエストが飛ぶことを確認
   - ボタンを連打すると、押すごとにリクエストが飛ぶのではなく、ローディング中はリクエストが飛ばないことを確認

## その他

特になし。

2022-03-01 23:58 UTC, tkomatsu requested changes

2022-03-01 23:58 UTC, tkomatsu commented on src/components/model/FollowerList.tsx
> +            return <FollowerStatus user={follower} />;
keyを追加してください！
consoleでwarningでてます。
![image](https://user-images.githubusercontent.com/46949817/156268414-df4a1c14-da2a-4f43-9ce2-3f69aadf55d7.png)

2022-03-01 23:58 UTC, tkomatsu commented on src/components/model/FollowerStatus.tsx
> +const FollowerStatus: React.VFC<{ user: User | null }> = ({ user }) => {
ステータスとアイコンが被ると視認性が下がるので、枠をつけるといいかも
枠の色は背景色とかがいいのかな
![image](https://user-images.githubusercontent.com/46949817/156268500-dd3559b4-b942-4508-86da-11a68aaf77a3.png)

2022-03-01 23:58 UTC, tkomatsu commented on src/components/model/FollowerStatus.tsx
> +const FollowerStatus: React.VFC<{ user: User | null }> = ({ user }) => {
ユーザーページに飛べるリンクになっているとよさそう
アイコンもしくはusernameをクリックするとそのユーザーのページに飛べるといいんじゃないでしょうか

2022-03-01 23:58 UTC, tkomatsu commented on src/components/model/UserCard.tsx
> +const UserCard: React.VFC<{
```ts
type Props = {
  param: string
}
```
みたいな形でPropの型定義をimport文の下あたりに書いてもらえると、コードが読みやすくなるかなと思います。
https://ptb.discord.com/channels/903993350322008085/904171247007588425/945277892764516403

2022-03-02 09:39 UTC, nafuka11 commented on src/components/model/FollowerList.tsx
> +            return <FollowerStatus user={follower} />;
4b49814 で `follower.id` をkeyとするよう修正しました！

2022-03-02 09:42 UTC, nafuka11 commented on src/components/model/FollowerStatus.tsx
> +const FollowerStatus: React.VFC<{ user: User | null }> = ({ user }) => {
d29d76f でboxShadowを使って枠線を表示するよう修正しました！
枠線の色は背景色としました。
![2022-03-02 18-41-20](https://user-images.githubusercontent.com/42476527/156336101-4d381614-f80a-4be2-a43a-52dfa20b6e7f.png)

修正に当たり、以下のリンクのコードを参考にしています。
- https://mui.com/components/avatars/#with-badge

2022-03-02 09:43 UTC, nafuka11 commented on src/components/model/FollowerStatus.tsx
> +const FollowerStatus: React.VFC<{ user: User | null }> = ({ user }) => {
6f08716 でアイコンをクリックすると `/users/{username}` に飛ぶよう修正しました！
アイコンの方がクリックしやすいので、usernameではなくアイコンにリンクを貼りました。

2022-03-02 09:44 UTC, nafuka11 commented on src/components/model/UserCard.tsx
> +const UserCard: React.VFC<{
1cdb926 にて修正しました！

2022-03-02 12:00 UTC, tkomatsu requested changes

2022-03-02 12:00 UTC, tkomatsu commented on src/components/model/FollowerList.tsx
> +const FollowerList: React.VFC<{ followers: User[] | null }> = ({
すみません、こっちもPropsの型作ってもらえますか:pray:

2022-03-02 12:00 UTC, tkomatsu commented on src/components/model/FollowerStatus.tsx
> +const FollowerStatus: React.VFC<{ user: User | null }> = ({ user }) => {
Propsの型定義して欲しいです:pray:

2022-03-02 12:00 UTC, tkomatsu commented on src/components/model/FollowerStatus.tsx
> +const FollowerStatus: React.VFC<{ user: User | null }> = ({ user }) => {
伝え方が下手ですみません:bow:
「もしくは」はどちらをクリックしてもリンクに飛ぶということのつもりでした
usernameでもリンクできるようにして欲しいです！

2022-03-02 12:00 UTC, tkomatsu commented on src/components/model/FollowerStatus.tsx
> +      <ChatBubble sx={{ fontSize: 24 }} color="disabled" />
colorで指定しているものは動作と一致しているべきな気もしますね。
disabledだと使えないのかと思ってしまうので、、。
defaultでいいのかも！

2022-03-02 12:00 UTC, tkomatsu commented on src/components/pages/UserProfile.tsx
> +      return res.data.id ? followApi.getUsersUserIDFollowing(res.data.id) : null
meを叩いているのに、followしているか確認するAPI叩くのおかしくないです？
1. meを叩いてとりあえずログインユーザー情報を取得
2. パスパラメータがあったらログインユーザーのusernameと一致するか確認
3. 違っていたらusernameでfetchする
4. フォローしているか確認する
だと思ったんですけど、これってどういうロジックですか？

2022-03-03 11:27 UTC, tkomatsu commented on src/components/pages/UserProfile.tsx
> +      return res.data.id ? followApi.getUsersUserIDFollowing(res.data.id) : null
`fetchUserFromUsername`が`/users/:username`で自分のページにアクセスしたときにも叩いてしまうことになっているので、無駄なリクエストを減らすようなロジックにしてもらえると！

2022-03-04 03:09 UTC, nafuka11 commented on src/components/model/FollowerStatus.tsx
> +const FollowerStatus: React.VFC<{ user: User | null }> = ({ user }) => {
04f1027 で修正しました！

2022-03-04 03:11 UTC, nafuka11 commented on src/components/model/FollowerList.tsx
> +const FollowerList: React.VFC<{ followers: User[] | null }> = ({
2d1848c で修正しました！

2022-03-04 03:11 UTC, nafuka11 commented on src/components/model/FollowerStatus.tsx
> +const FollowerStatus: React.VFC<{ user: User | null }> = ({ user }) => {
2d1848c で修正しました！

2022-03-04 03:16 UTC, nafuka11 commented on src/components/model/FollowerStatus.tsx
> +      <ChatBubble sx={{ fontSize: 24 }} color="disabled" />
defaultだと色が黒く印象が強いかなと思いましたので、neutralを使うように変更しました！ c11bda2

default
<img src="https://user-images.githubusercontent.com/42476527/156692495-4140bc91-295c-4dab-9ad5-f52fb352b007.png" width="360"/>
neutral
![2022-03-04 12-14-39](https://user-images.githubusercontent.com/42476527/156692519-102d63e7-5d15-4976-9972-b2cee675f406.png)

2022-03-04 03:18 UTC, nafuka11 commented on src/components/pages/UserProfile.tsx
> +      return res.data.id ? followApi.getUsersUserIDFollowing(res.data.id) : null
完全理解。
b94bc15 のあたりで直しました！

2022-03-04 03:22 UTC, nafuka11 commented
mainにmergeされた #19 の変更を取り込みました。
実際に動かしてみて不具合が発生した箇所を修正しています。
具体的には、
- APIリクエストにwithCredintialオプションを追加
- Follow/Unfollowに使用するAPIのuserID指定が誤っていたのを修正（ownerId → targetId）
- Followしているかの確認で、Followしていない時catch節で404を捕捉できてなかったのを修正

2022-03-04 04:02 UTC, tkomatsu commented on src/components/pages/UserProfile.tsx
> +        return fetchIsFollower(ownerId, res.data.id)
書き方として気になるのですが、returnで`fetchFollowers()`と`fetchIsFollower()`を返しているのはなんでですか？
どちらも返り値がないようなので、return文と関数呼び出しは分けた方がわかりやすいなと思いました。

2022-03-04 04:02 UTC, tkomatsu commented on src/components/pages/UserProfile.tsx
> +      if (res.data.id === ownerId) {
自分のページを`/users/:username`でアクセスしたときに`getUsersUsername()`を叩く必要ってありますか？
以下の条件分岐が一番少ないと思います。
1. `/home`または、`/users/:username`に自分のページとしてアクセスした時
    1. `/me`を叩く
    2. `/users/:userId/followings`を叩く
2. 自分以外のページにアクセスするとき
    1. `/me`を叩く
    2. `/users/:username`を叩く
    3. `/users/:userId/following/:targetUserId`を叩く

今のコードだと、1の`/users/:username`に自分のページとしてアクセスした時に3回api叩く場合があるように見えます。

2022-03-05 15:15 UTC, nafuka11 commented on src/components/pages/UserProfile.tsx
> +      if (res.data.id === ownerId) {
a4bf242 で meの時 /users/:username を叩かないよう修正しました。

2022-03-05 15:15 UTC, nafuka11 commented on src/components/pages/UserProfile.tsx
> +        return fetchIsFollower(ownerId, res.data.id)
a4bf242 でreturnしないよう修正しました。

2022-03-06 01:23 UTC, tkomatsu approved these changes
LGTM!

2022-03-06 01:23 UTC, merged