add username in useEffect
RIFT-tokyo/transcendence-front pull request #34
Opened 2022-03-07 11:58 UTC by sasakiyudai

## チケットへのリンク
#32 
## やったこと
usernameをuseEffectの依存関係に追加
## やらないこと

## テスト
フォローリストのユーザーをクリックしてちゃんと変わるか確認
## その他

2022-03-07 12:13 UTC, tkomatsu commented
以下で表示されるユーザー情報に変化なしです。
1. ログインする（intraとパスワードどちらでも可）
2. 自分のusernameを使って`/users/:username`にアクセスする
3. Followingsにいるユーザーを選択する
4. URLは選択した他のユーザーのusernameになっているが、内容は自分のまま

2022-03-07 12:24 UTC, tkomatsu commented
ユーザー情報は変わっているけれど、EDIT PROFILEボタンとFollowingsが表示されたままになっているね。
FOLLOW/UNFOLLOWボタン表示になるのと、Followingsは非表示にする！

2022-03-08 12:07 UTC, sasakiyudai commented
@tkomatsu 
> ユーザー情報は変わっているけれど、EDIT PROFILEボタンとFollowingsが表示されたままになっているね。
FOLLOW/UNFOLLOWボタン表示になるのと、Followingsは非表示にする！
これ自分の方ではちゃんと動きます。

2022-03-08 23:27 UTC, tkomatsu commented
`localhost:4212/home`からは問題なく動くのはわかっている。
`tkomatsu`でログインしている状態で、`localost:4212/home`ではなく、`localhost:4212/users/tkomatsu`でアクセスした時は`/home`と同じ表示になる。
その状態で、Followingsのリストから他のユーザーに遷移すると変わらないって話です。

https://user-images.githubusercontent.com/46949817/157342887-9447827d-8ed7-4574-b3f0-36a1122f1a2e.mov

2022-03-09 11:55 UTC, tkomatsu requested changes
２点直して欲しいです:pray:

2022-03-09 11:55 UTC, tkomatsu commented on src/components/pages/UserProfile.tsx
> +        fetchFollowers(res.data.id);
他者のプロフィール表示の時にFollowingsのためのAPIを叩く必要はなさそう。

2022-03-09 11:55 UTC, tkomatsu commented on src/components/pages/UserProfile.tsx
>    const fetchFollowers = async (ownerId: number) => {
今回の内容とは直接関係ないんですが、FollowersではなくFollowingsが正しいので、ついでに関数名を直してもらえますか。

2022-03-09 11:58 UTC, sasakiyudai commented on src/components/pages/UserProfile.tsx
>    const fetchFollowers = async (ownerId: number) => {
[fdc1d4d](https://github.com/RIFT-tokyo/transcendence-front/pull/34/commits/fdc1d4d9a2ae4125347eedf4d869eec2dcc22002)dedone

2022-03-09 11:58 UTC, sasakiyudai commented on src/components/pages/UserProfile.tsx
> +        fetchFollowers(res.data.id);
[fdc1d4d](https://github.com/RIFT-tokyo/transcendence-front/pull/34/commits/fdc1d4d9a2ae4125347eedf4d869eec2dcc22002)dedone

2022-03-09 12:00 UTC, tkomatsu approved these changes
LGTM!

2022-03-09 12:00 UTC, merged