not navigate on settings/
RIFT-tokyo/transcendence-front pull request #42
Opened 2022-03-15 14:19 UTC by sasakiyudai

## チケットへのリンク
fix #38 
## やったこと
settings直下をNavigateでなくAccountそのままのにした
## やらないこと

## テスト

## その他
正直微妙。代替案あれば是非。

2022-03-16 11:41 UTC, tkomatsu requested changes
フォーマット修正だけお願いします！
動作は問題なしです！

2022-03-16 11:41 UTC, tkomatsu commented on src/App.tsx
> +                <Route index element={<Navigate to="account" replace />} />
細かいですがインデント1段下げてください！

2022-03-16 11:44 UTC, sasakiyudai commented on src/App.tsx
> +                <Route index element={<Navigate to="account" replace />} />
sorry. here [6c39051](https://github.com/RIFT-tokyo/transcendence-front/pull/42/commits/6c39051717da31766374540f355dae264931f561)

2022-03-17 11:08 UTC, tkomatsu approved these changes
LGTM!

2022-03-17 11:08 UTC, merged