Password change config
RIFT-tokyo/transcendence-front pull request #49
Opened 2022-04-06 13:43 UTC by tkomatsu

## チケットへのリンク
fix #47 
## やったこと
パスワード更新の機能を追加しました
## やらないこと

## テスト
1. 設定画面からセキュリティに遷移する
2. バリデーションの確認
    1. フォームのいずれかを空にした状態で更新するとアラートが表示される
    2. `new password`と`confirm password`が一致しない場合にアラートが表示される
3. パスワード更新処理の確認
    1. `current password`が間違えていた場合にアラートが表示される
    2. 正しいパスワードを入力し、更新処理を成功させる
    3. 一度ログアウトし、更新したパスワードでログインできることを確認する

## その他

2022-04-10 12:37 UTC, nafuka11 requested changes

2022-04-10 12:37 UTC, nafuka11 commented on src/components/model/SecuritySetting.tsx
> +  const [confirmPassword, setConfirmPassword] = React.useState<string | null>(null);
Security画面にて、コンソールに以下のエラーが表示されました。
```
Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
```
passwordの初期値が `null` だからかなと思います。
`React.useState<string | null>(null)` は、 `React.useState<string>("")` とすると上記のエラーは発生しないようです。

2022-04-10 12:37 UTC, nafuka11 commented on src/components/model/SecuritySetting.tsx
> +      alert('パスワードの更新に失敗しました');
alertの文言が日本語の理由を知りたいです。
英語の方が統一感があるように思います。
alertが一時的な実装でしたら全く問題ないです。

2022-04-10 12:37 UTC, nafuka11 commented on src/components/model/SecuritySetting.tsx
> +      await authApi.putAuthPassword(data, { withCredentials: true });
パスワード変更が完了したかどうか、現状ユーザ側から分からないです。
完了したら alert 等で通知すると、分かりやすいと思います。
（ですが、必要な機能は満たしているのでこのままでも問題ないと思います）

2022-04-10 12:37 UTC, nafuka11 commented on src/components/model/SecuritySetting.tsx
> +        >
UserCardのように、リクエスト中ならdisabledにすると、
ボタン連打を防げるかなと思います。

2022-04-10 12:48 UTC, tkomatsu commented on src/components/model/SecuritySetting.tsx
> +      alert('パスワードの更新に失敗しました');
alertは最終的に使わないようにしたく、とりあえずの実装でした。
ただ、成功時もわからないのでトースト通知を実装しちゃおうと思います。

2022-04-10 12:48 UTC, tkomatsu commented on src/components/model/SecuritySetting.tsx
> +      await authApi.putAuthPassword(data, { withCredentials: true });
エラー時のアラートの修正に合わせてトースト通知実装します

2022-04-11 12:54 UTC, nafuka11 commented on src/components/model/SecuritySetting.tsx
> +  const [confirmPassword, setConfirmPassword] = React.useState<string | null>(null);
02205c2 で修正確認しました。

2022-04-11 13:02 UTC, nafuka11 commented on src/components/model/SecuritySetting.tsx
> +      await authApi.putAuthPassword(data, { withCredentials: true });
b32e2a3 で確認しました！

2022-04-11 13:02 UTC, nafuka11 commented on src/components/model/SecuritySetting.tsx
> +      alert('パスワードの更新に失敗しました');
b32e2a3 で確認しました！

2022-04-11 13:12 UTC, nafuka11 commented on src/components/model/SecuritySetting.tsx
> +        >
b32e2a3 での対応ありがとうございます！
`isRequesting` がtrueのときAPIコールがされないと理解しました。

UserCardだと `isRequesting` がtrueのとき、buttonがdisabled=trueになってるのですが、そこは特に合わせないという認識で合っていますか？

2022-04-11 13:14 UTC, tkomatsu commented on src/components/model/SecuritySetting.tsx
> +        >
あってます

2022-04-11 13:18 UTC, nafuka11 approved these changes
パスワード変更できること、
エラー・成功通知がSnackbarで表示されることを確認しました！
また、SignUp画面でのエラーもSnackbarで表示されることを確認しました。

Snackbarかっこいいです……！

2022-04-11 13:19 UTC, merged