User status websocket
RIFT-tokyo/transcendence-front pull request #61
Opened 2022-04-15 15:19 UTC by sasakiyudai

## チケットへのリンク
fix #60
## やったこと
websocketによるuserStatus更新
sqlのlogがうるさすぎるので削除

## やらないこと

## テスト
・env, front, api, docs 全てをuser-status-websocketにする
・cp example.env .env
・compose up --build
・ウィンドウを二つ開く(sessionを変えるため少なくとも片方はシークレットウィンドウにする)
・片方のユーザーで他方のユーザーをfollow
(test for userStatus event)
・followされた方でウィンドウを閉じたりログインしたりでuserStatusの色が変わるかcheck
・games画面に行って色が変わるかcheck

https://user-images.githubusercontent.com/66932739/163588658-fd2fa47b-f2f4-40ae-a425-b065958a33a0.mp4

(test for ping, pong event)
・games画面でemitするようにし、contexts/SocketContext.tsxの定義にある通りとりあえずconsoleにpongが表示されるかcheck

## その他
・userProfileのfollowersの変更が汚い。useEffect二つ使ったのは本当はやりたくない。(なんとなく)。うまいこと書けないかなー。
・socketIOclientのauthでuserIDっていう情報を渡すことができたけど、authってこうやって使ってもいいんかなー。
・お楽しみください

2022-04-17 12:51 UTC, tkomatsu commented
以下の場合でステータスの表示が更新されないです。
1. 2つのブラウザ(A, B)を開く
2. Aでログインする
3. Bでログインする
4. A, Bともにステータスがオフラインのまま

一度ゲーム画面に遷移するとゲーム表示に切り替わり、別ページに遷移するとオンライン表示には切り替わります。

また、mainブランチとのコンフリクトも発生したので併せて修正お願いします。

2022-04-17 14:58 UTC, sasakiyudai commented
> 以下の場合でステータスの表示が更新されないです。
> 
> 1. 2つのブラウザ(A, B)を開く
> 2. Aでログインする
> 3. Bでログインする
> 4. A, Bともにステータスがオフラインのまま
> 
> 一度ゲーム画面に遷移するとゲーム表示に切り替わり、別ページに遷移するとオンライン表示には切り替わります。
> 
> また、mainブランチとのコンフリクトも発生したので併せて修正お願いします。

もろもろ修正しました

2022-04-18 13:15 UTC, tkomatsu requested changes

2022-04-18 13:15 UTC, tkomatsu commented on src/contexts/SocketContext.tsx
> +export const ContextProvider: FC = ({ children }) => {
ContextProviderという名前ですが、ソケット以外のものもこのプロバイダに含める予定ですか？
websocketだけに使うのであれば、別の名前にして欲しいです。

2022-04-18 13:15 UTC, tkomatsu commented on src/contexts/SocketContext.tsx
> +      console.log('pong');
consoleへの出力はデバッグ用ですか？そうであれば削除してください。
実装上必要なものであれば、snackbar等の実装をしてください。

2022-04-18 13:15 UTC, tkomatsu commented on src/contexts/SocketContext.tsx
> +      `${process.env.REACT_APP_SOCKET_URL!}/users`,
`/users`をconfigで定義して欲しいです。
コードにベタで書かない方法が望ましいです。

2022-04-18 13:15 UTC, tkomatsu commented on src/components/pages/UserProfile.tsx
> +      client.users.on('userStatus', onUserStatus);
イベント名はconstantとして定義してください。
AsyncAPIの自動生成でもいけるかもです。

2022-04-18 13:15 UTC, tkomatsu commented on src/components/pages/UserProfile.tsx
> +
不要な改行です。

2022-04-18 13:15 UTC, tkomatsu commented on src/components/pages/Pong.tsx
> +      client.users.emit('userStatus', { status: 'game', userID: authUser?.id });
payloadも型定義（インターフェースかも？）をしてください。

2022-04-20 12:05 UTC, sasakiyudai commented on src/contexts/SocketContext.tsx
> +export const ContextProvider: FC = ({ children }) => {
[5564146](https://github.com/RIFT-tokyo/transcendence-front/pull/61/commits/55641461aad34a282f103b1ab7448f09f3789ab4)で対応

2022-04-20 12:05 UTC, sasakiyudai commented on src/contexts/SocketContext.tsx
> +      console.log('pong');
[5564146](https://github.com/RIFT-tokyo/transcendence-front/pull/61/commits/55641461aad34a282f103b1ab7448f09f3789ab4)で対応

2022-04-20 12:05 UTC, sasakiyudai commented on src/contexts/SocketContext.tsx
> +      `${process.env.REACT_APP_SOCKET_URL!}/users`,
[5564146](https://github.com/RIFT-tokyo/transcendence-front/pull/61/commits/55641461aad34a282f103b1ab7448f09f3789ab4)で対応

2022-04-20 12:05 UTC, sasakiyudai commented on src/components/pages/UserProfile.tsx
> +      client.users.on('userStatus', onUserStatus);
[5564146](https://github.com/RIFT-tokyo/transcendence-front/pull/61/commits/55641461aad34a282f103b1ab7448f09f3789ab4)で対応

2022-04-20 12:05 UTC, sasakiyudai commented on src/components/pages/UserProfile.tsx
> +
[5564146](https://github.com/RIFT-tokyo/transcendence-front/pull/61/commits/55641461aad34a282f103b1ab7448f09f3789ab4)で対応

2022-04-20 12:07 UTC, sasakiyudai commented on src/components/pages/Pong.tsx
> +      client.users.emit('userStatus', { status: 'game', userID: authUser?.id });
MTGの通り今回のPRではやらないことになりました

2022-04-22 08:47 UTC, tkomatsu approved these changes

2022-04-22 08:47 UTC, tkomatsu commented
LGTM

2022-04-22 08:47 UTC, merged