アチーブメントとマッチ履歴の追加
RIFT-tokyo/transcendence-front pull request #64
Opened 2022-04-24 07:05 UTC by tkomatsu

## チケットへのリンク
https://github.com/orgs/RIFT-tokyo/projects/1#card-76202980
## やったこと
- アチーブメントの追加
- マッチ履歴の追加
## やらないこと
- アチーブメントの追加機能（今後ゲーム終了時にステータスを見て付与する機能を追加する）
- マッチ履歴の追加（ゲーム開始時に列を作成し、終了時に`end_at`カラムを埋める処理を追加する）
- ランキング表示
- レベル表示
## テスト
1. 下準備
    1. front, apiをビルドし直す
    2. `docker compose exec api yarn migration:run`でマイグレーションを実行する
    3. `docker compose exec api yarn seed:run -s AddAchievements`でアチーブメントのデータを追加する
    4. `user_achievements_achievement`テーブルに取得したアチーブメントとして追加する(1 or 2しかないです)
    5. `match`にマッチ履歴を追加する
6. アチーブメントの挙動確認
    7. ホーム画面で、取得したアチーブメントが表示されているか確認する
    8. アイコンをクリックし、モーダルで詳細が表示されるか確認する
9. マッチ履歴の挙動確認
    10. 履歴が時系列で表示されることを確認する
    11. `end_at`がnullのデータ（ゲーム途中で終了してしまって勝敗がついていない）が表示されないことを確認する
    12. 勝敗がついているデータでは勝者の文字が太くなっていることを確認する

## その他

2022-04-24 16:51 UTC, nafuka11 requested changes
アチーブメントとマッチ履歴、超かっこいいです……！

解像度1920 × 1080のディスプレイだと、Achievementsが見切れてしまうようです。
もう少しUserCardのAvatarが小さいか、FollowerListの幅が小さいと見きれなそうです。
（どこまでのサイズを対象とするかにもよるので、このサイズを対象外とするならば、それでもいいと思います）
![2022-04-25 01-38-10-small](https://user-images.githubusercontent.com/42476527/164987114-d80e5374-a027-4f1f-8b82-a10fec087e7a.png)

その他気になった点は以下に書いています。

2022-04-24 16:51 UTC, nafuka11 commented on src/components/model/MatchHistory.tsx
> +                  </Avatar>
小さい表示のAvatarは、FollowerStatusでも使いますし、今後チャットで使いそうに思います。
このPRでなくても、どこかのタイミングでComponentとした方がいいかもしれません。

2022-04-24 16:51 UTC, nafuka11 commented on src/components/model/MatchHistory.tsx
> +                </Stack>
重複は2箇所しかないですが、後々の変更しやすさを考えるとComponentにするのもありかもと思いました。

2022-04-24 16:51 UTC, nafuka11 commented on src/components/model/MatchHistory.tsx
> +                  </Typography>
アバターとuser名にリンクがあると、気になる相手のページにすぐ飛べて便利だと思います。

2022-04-24 23:21 UTC, tkomatsu commented on src/components/model/MatchHistory.tsx
> +                  </Avatar>
Avatarは確かにコンポーネントにしてもいいかもですね。
ただ、サイズとか他のpropsを渡すこと考えるとありがたみがどこまであるのかはわかんないです。

2022-04-24 23:21 UTC, tkomatsu commented on src/components/model/MatchHistory.tsx
> +                </Stack>
重複してないと思うのですが、どの部分で共通化できますか？

2022-04-25 04:47 UTC, nafuka11 commented on src/components/model/MatchHistory.tsx
> +                </Stack>
すみません、説明が足りておりませんでした。
PlayerのAvatarとplayer名の部分です。
![2022-04-25 13-44-40-small](https://user-images.githubusercontent.com/42476527/165022558-8c4f754d-efd4-46a5-813a-6100e23a1f8a.png)
user情報と勝利したかどうかのbooleanをpropsに渡すと共通化できるかなと思いました。

2022-04-25 04:51 UTC, nafuka11 commented on src/components/model/MatchHistory.tsx
> +                  </Typography>
2324cb7 にて変更を確認しました！

2022-04-25 05:01 UTC, nafuka11 commented on src/components/model/MatchHistory.tsx
> +                  </Avatar>
> ただ、サイズとか他のpropsを渡すこと考えるとありがたみがどこまであるのかはわかんないです。

確かにそうですね……。
今後のAvatarをどう使っていくかによりそうです。
一旦無かったことにさせてください。

2022-04-26 12:22 UTC, nafuka11 commented on src/components/model/MatchHistory.tsx
> +                </Stack>
本件、RankingとLevelを実装時にComponent化した方が共通化しやすいため、一旦保留にします！

2022-04-26 12:54 UTC, nafuka11 approved these changes
画面が1920 × 1080に収まること、およびfooterの表示を確認しました……！
とてもかっこいいです。ありがとうございます！

2022-04-26 12:54 UTC, merged